namespace Player.Commands
{
    /// <summary>
    /// Result returned by <see cref="PlayerCommandService"/> when processing a chat message.
    /// </summary>
    public readonly struct PlayerCommandHandleResult
    {
        public static PlayerCommandHandleResult NotACommand() => new PlayerCommandHandleResult(false, false, PlayerCommandServiceError.None, string.Empty);

        public PlayerCommandHandleResult(bool isCommand, bool success, PlayerCommandServiceError error, string feedbackMessage)
        {
            IsCommand = isCommand;
            Success = success;
            Error = error;
            FeedbackMessage = feedbackMessage;
        }

        /// <summary>
        /// Indicates whether the input text was treated as a command.
        /// </summary>
        public bool IsCommand { get; }

        /// <summary>
        /// Indicates whether the command executed successfully.
        /// </summary>
        public bool Success { get; }

        /// <summary>
        /// Provides additional context when <see cref="Success"/> is <c>false</c>.
        /// </summary>
        public PlayerCommandServiceError Error { get; }

        /// <summary>
        /// Human-readable feedback describing the outcome.
        /// </summary>
        public string FeedbackMessage { get; }
    }

    /// <summary>
    /// Enumerates the possible error states generated by <see cref="PlayerCommandService"/>.
    /// </summary>
    public enum PlayerCommandServiceError
    {
        /// <summary>
        /// No error occurred or the input was not a command.
        /// </summary>
        None = 0,
        /// <summary>
        /// The resolved command name does not exist in the registry.
        /// </summary>
        UnknownCommand = 1,
        /// <summary>
        /// The player lacks the required rank to execute the command.
        /// </summary>
        Unauthorized = 2,
        /// <summary>
        /// The command input failed validation.
        /// </summary>
        InvalidSyntax = 3,
        /// <summary>
        /// The command raised an unexpected exception or reported an execution failure.
        /// </summary>
        ExecutionError = 4,
        /// <summary>
        /// Required infrastructure (rank or chat services) was not available.
        /// </summary>
        ServiceUnavailable = 5,
    }
}
