using System;
using System.Collections.Generic;
using UnityEngine;
using NPC;
using Status.Poison;

namespace Combat
{
    [Serializable]
    public struct ElementalModifier
    {
        public SpellElement element;
        [Range(0, 100)] public int protectionPercent;
        public int bonusPercent;
    }

    /// <summary>
    /// Defines combat statistics for an NPC.
    /// </summary>
    [CreateAssetMenu(menuName = "Combat/NPC Profile")]
    public class NpcCombatProfile : ScriptableObject
    {
        public int AttackLevel = 1;
        public int StrengthLevel = 1;
        public int DefenceLevel = 1;
        public int MagicLevel = 1;
        public int HitpointsLevel = 10;
        public int MeleeDefence;
        public int RangeDefence;
        public int MagicDefence;
        public int AttackSpeedTicks = 4;
        public float RespawnSeconds;
        public DamageType AttackType = DamageType.Melee;
        public CombatStyle Style = CombatStyle.Accurate;
        [Tooltip("If true, this NPC will automatically attack nearby players.")]
        public bool IsAggressive;
        [Tooltip("Seconds to keep aggro on a target after it moves beyond the chase radius.")]
        public float AggroTimeoutSeconds = 5f;

        [Tooltip("Maximum number of targets this NPC can attack at once.")]
        public int MaxConcurrentTargets = 1;

        [Tooltip("Multiplier applied to threat generated by player characters.")]
        public float PlayerAggroWeight = 1f;

        /// <summary>
        /// Faction that this NPC belongs to. Defaults to <see cref="FactionId.Neutral"/>.
        /// </summary>
        public FactionId Faction = FactionId.Neutral;

        [Header("Poison")]
        public bool IsPoisonous;
        public PoisonConfig OnHitPoison;
        [Range(0f, 1f)] public float PoisonChance = 0.25f;
        public bool PoisonRequiresDamage = true;

        public List<ElementalModifier> elementalModifiers = new();
    }
}
