using System;
using System.Collections.Generic;
using UnityEngine;
using NPC;
using Status.Poison;

namespace Combat
{
    [Serializable]
    public struct ElementalModifier
    {
        public SpellElement element;
        [Range(0, 100)] public int protectionPercent;
        public int bonusPercent;
    }

    /// <summary>
    /// Defines combat statistics for an NPC.
    /// </summary>
    [CreateAssetMenu(menuName = "Combat/NPC Profile")]
    public class NpcCombatProfile : ScriptableObject
    {
        public int AttackLevel = 1;
        public int StrengthLevel = 1;
        public int DefenceLevel = 1;
        [Tooltip("Base ranged level used for accuracy and max hit rolls when the NPC uses ranged attacks.")]
        public int RangedLevel = 1;
        public int MagicLevel = 1;
        public int HitpointsLevel = 10;
        public int MeleeDefence;
        public int RangeDefence;
        public int MagicDefence;
        public int AttackSpeedTicks = 4;
        public float RespawnSeconds;
        public DamageType AttackType = DamageType.Melee;
        public CombatStyle Style = CombatStyle.Accurate;
        [Tooltip("If true, this NPC will automatically attack nearby players.")]
        public bool IsAggressive;
        [Tooltip("Seconds to keep aggro on a target after it moves beyond the chase radius.")]
        public float AggroTimeoutSeconds = 5f;

        [Header("Attack Range")]
        [Tooltip("Preferred distance when using ranged attacks. Defaults to a mid-range bow distance if unset.")]
        [Min(0f)] public float RangedAttackRange = 6f;
        [Tooltip("Preferred distance when using magic attacks. Defaults to a typical strike spell range if unset.")]
        [Min(0f)] public float MagicAttackRange = 7f;

        [Tooltip("When enabled the NPC ignores freeze effects while still taking damage.")]
        public bool NotFreezable;

        [Tooltip("Maximum number of targets this NPC can attack at once.")]
        public int MaxConcurrentTargets = 1;

        [Tooltip("Multiplier applied to threat generated by player characters.")]
        public float PlayerAggroWeight = 1f;

        /// <summary>
        /// Faction that this NPC belongs to. Defaults to <see cref="FactionId.Neutral"/>.
        /// </summary>
        public FactionId Faction = FactionId.Neutral;

        [Header("Poison")]
        public bool IsPoisonous;
        public PoisonConfig OnHitPoison;
        [Range(0f, 1f)] public float PoisonChance = 0.25f;
        public bool PoisonRequiresDamage = true;

        public List<ElementalModifier> elementalModifiers = new();

        private const float MINIMUM_ATTACK_RANGE = 0.1f;
        private const float DEFAULT_RANGED_RANGE = 6f;
        private const float DEFAULT_MAGIC_RANGE = 7f;

        /// <summary>
        /// Returns the preferred attack distance based on the configured <see cref="AttackType"/>,
        /// falling back to sensible defaults when no explicit range has been supplied.
        /// </summary>
        public float GetPreferredAttackRange()
        {
            return AttackType switch
            {
                DamageType.Ranged => Mathf.Max(MINIMUM_ATTACK_RANGE,
                    RangedAttackRange > 0f ? RangedAttackRange : DEFAULT_RANGED_RANGE),
                DamageType.Magic => Mathf.Max(MINIMUM_ATTACK_RANGE,
                    MagicAttackRange > 0f ? MagicAttackRange : DEFAULT_MAGIC_RANGE),
                _ => Mathf.Max(MINIMUM_ATTACK_RANGE, CombatMath.MELEE_RANGE)
            };
        }
    }
}
