using UnityEngine;
using NPC;

namespace Combat
{
    /// <summary>
    /// Defines combat statistics for an NPC.
    /// </summary>
    [CreateAssetMenu(menuName = "Combat/NPC Profile")]
    public class NpcCombatProfile : ScriptableObject
    {
        public int AttackLevel = 1;
        public int StrengthLevel = 1;
        public int DefenceLevel = 1;
        public int MagicLevel = 1;
        public int HitpointsLevel = 10;
        public int MeleeDefence;
        public int RangeDefence;
        public int MagicDefence;
        public int AttackSpeedTicks = 4;
        public float RespawnSeconds;
        public DamageType AttackType = DamageType.Melee;
        public CombatStyle Style = CombatStyle.Accurate;
        [Tooltip("If true, this NPC will automatically attack nearby players.")]
        public bool IsAggressive;
        [Tooltip("Maximum distance in tiles before an aggressive NPC loses aggro.")]
        public float AggroRange = 5f;

        [Tooltip("Maximum number of targets this NPC can attack at once.")]
        public int MaxConcurrentTargets = 1;

        [Tooltip("Multiplier applied to threat generated by player characters.")]
        public float PlayerAggroWeight = 1f;

        /// <summary>
        /// Faction that this NPC belongs to. Defaults to <see cref="FactionId.Neutral"/>.
        /// </summary>
        public FactionId Faction = FactionId.Neutral;
    }
}
