using System;
using UnityEngine;
using Inventory;

namespace Combat.Ranged
{
    /// <summary>
    /// Categories describing the behaviour of ranged weapons. Used for animation logic and
    /// speed groupings so OSRS-style attack speeds can be mirrored without hardcoding item IDs.
    /// </summary>
    public enum RangedWeaponCategory
    {
        Longbow,
        Shortbow,
        Crossbow,
        ThrowingKnife,
        Dart,
        Javelin,
        Chinchompa,
        Gunpowder,
        Other
    }

    /// <summary>
    /// Ammunition groupings exposed by <see cref="AmmunitionData"/>. Weapon definitions link to the
    /// category they can consume so expansion simply requires creating additional ScriptableObjects.
    /// </summary>
    public enum AmmunitionCategory
    {
        None,
        Arrow,
        Bolt,
        ThrowingKnife,
        Dart,
        Javelin,
        Chinchompa
    }

    /// <summary>
    /// Scriptable representation of a ranged weapon. Stores projectile, timing and modifier data so
    /// gameplay code remains fully data-driven.
    /// </summary>
    [CreateAssetMenu(menuName = "Combat/Ranged/Weapon", fileName = "RangedWeaponData")]
    public class RangedWeaponData : ScriptableObject
    {
        [Header("Identification")]
        [Tooltip("Optional explicit item id override. When empty the linked ItemData id is used.")]
        [SerializeField] private string weaponIdOverride;
        [Tooltip("Item definition that owns this ranged weapon behaviour.")]
        [SerializeField] private ItemData weaponItem;
        [Tooltip("Logical category used for grouping speeds/animations.")]
        public RangedWeaponCategory category = RangedWeaponCategory.Other;
        [Tooltip("Ammunition category this weapon consumes. Set to None for thrown weapons that use the weapon stack itself.")]
        public AmmunitionCategory ammunitionCategory = AmmunitionCategory.Arrow;
        [Tooltip("If true the weapon consumes the equipped weapon stack (darts/knives) rather than checking the ammo slot.")]
        public bool consumesWeaponStack;

        [Header("Combat Ticks")]
        [Tooltip("Attack speed expressed in OSRS ticks (0.6s each).")]
        [Min(1)] public int attackSpeedTicks = 4;
        [Tooltip("Ticks spent drawing the weapon before the projectile is fired. Allows OSRS style draw delays.")]
        [Min(0f)] public float drawTicks = 1f;
        [Tooltip("Base projectile range measured in tiles (64 world units). Overrides can be provided per ammo.")]
        [Min(1f)] public float baseRangeTiles = 7f;

        [Header("Projectiles")]
        [Tooltip("Projectile prefab spawned when the shot is released. Must contain a RangedProjectile component.")]
        public GameObject projectilePrefab;
        [Tooltip("Impact VFX instantiated when the projectile successfully lands. Optional.")]
        public GameObject impactVfxPrefab;
        [Tooltip("Units per second travelled by the projectile before modifiers are applied.")]
        [Min(0.1f)] public float projectileSpeed = 16f;

        [Header("Formula Modifiers")]
        [Tooltip("Multiplicative bonus applied to the attack roll generated by CombatMath.")]
        [Min(0f)] public float accuracyMultiplier = 1f;
        [Tooltip("Multiplicative bonus applied to the damage roll.")]
        [Min(0f)] public float damageMultiplier = 1f;
        [Tooltip("Additional tiles added to the base range when the weapon is equipped. Allows longbows to outrange shortbows.")]
        public float rangeBonusTiles;

        [Header("Recovery & Consumption")]
        [Tooltip("Chance to recover ammo after a successful hit when the projectile can be reclaimed.")]
        [Range(0f, 1f)] public float recoveryChanceOnHit = 0.5f;
        [Tooltip("Chance to recover ammo after a miss. Usually lower than hit recovery.")]
        [Range(0f, 1f)] public float recoveryChanceOnMiss = 0.2f;
        [Tooltip("If true, recovered ammo is spawned in the world when the inventory is full.")]
        public bool spawnRecoveryAsGroundItem = true;

        [Header("Ammo Restrictions")]
        [Tooltip("When true the allowed ammunition list becomes authoritative. Only entries explicitly listed are permitted.")]
        public bool restrictAmmoByList;
        [Tooltip("Specific ammunition assets this weapon is allowed to fire when restriction mode is enabled.")]
        public AmmunitionData[] allowedAmmunition = Array.Empty<AmmunitionData>();
        [Tooltip("Ammunition definitions the weapon can never use even when restriction mode is disabled.")]
        public AmmunitionData[] blockedAmmunition = Array.Empty<AmmunitionData>();

        [Header("Feedback")]
        [Tooltip("Optional sound effect identifier consumed by SoundManager when the projectile is released.")]
        public string releaseSoundId;
        [Tooltip("Hook for bespoke on-hit behaviour (poison, secondary projectiles, etc.).")]
        public RangedSpecialEffect specialEffect;

        /// <summary>
        /// Resolved weapon id using the override when supplied, otherwise the linked item id.
        /// </summary>
        public string WeaponId => !string.IsNullOrWhiteSpace(weaponIdOverride)
            ? weaponIdOverride
            : weaponItem != null ? weaponItem.id : name;

        /// <summary>
        /// Direct reference to the backing ItemData asset when available.
        /// </summary>
        public ItemData WeaponItem => weaponItem;

        /// <summary>
        /// Convenience property returning the attack interval in seconds.
        /// </summary>
        public float AttackIntervalSeconds => attackSpeedTicks * CombatMath.TICK_SECONDS;

        /// <summary>
        /// Returns true when the supplied ammunition asset is considered valid for this weapon.
        /// Restriction mode enforces an allow-list while the block list functions regardless of the toggle.
        /// </summary>
        /// <param name="ammo">Ammunition definition resolved from the currently equipped stack.</param>
        public bool IsAmmoAllowed(AmmunitionData ammo)
        {
            if (ammo == null)
                return true;

            if (restrictAmmoByList)
            {
                if (allowedAmmunition == null || allowedAmmunition.Length == 0)
                    return false;

                bool found = false;
                for (int i = 0; i < allowedAmmunition.Length; i++)
                {
                    if (allowedAmmunition[i] == ammo)
                    {
                        found = true;
                        break;
                    }
                }

                if (!found)
                    return false;
            }

            if (blockedAmmunition != null)
            {
                for (int i = 0; i < blockedAmmunition.Length; i++)
                {
                    if (blockedAmmunition[i] == ammo)
                        return false;
                }
            }

            return true;
        }

        private void OnValidate()
        {
            attackSpeedTicks = Mathf.Max(1, attackSpeedTicks);
            drawTicks = Mathf.Max(0f, drawTicks);
            baseRangeTiles = Mathf.Max(1f, baseRangeTiles);
            projectileSpeed = Mathf.Max(0.1f, projectileSpeed);
            accuracyMultiplier = Mathf.Max(0f, accuracyMultiplier);
            damageMultiplier = Mathf.Max(0f, damageMultiplier);

            allowedAmmunition ??= Array.Empty<AmmunitionData>();
            blockedAmmunition ??= Array.Empty<AmmunitionData>();

            if (weaponItem != null && string.IsNullOrWhiteSpace(weaponIdOverride))
                weaponIdOverride = weaponItem.id;
        }
    }
}
